### ISSUE TITLE
Raw HTML is not escaped in the web output

### ISSUE THREAD

**Issue by igorpavlov** [bagwanpankaj/humongous#18]
If I store raw HTML in Mongo, it is not escaped in Humongous UI. For example, scripts are executed.

![screen shot 2015-11-11 at 13 28 53](https://cloud.githubusercontent.com/assets/3973243/11092073/3a1d773a-8878-11e5-85fd-f077f7f8d7da.png)

**Comment by bagwanpankaj** [comment]
Good point. But due to other commitments, I may not be able to look into this sooner. Request you to fix and raise a pull request I will be happy merge

**Comment by bagwanpankaj** [comment]
I think you are confusing open source `Humongous`, a mongodb database browser with service https://app.humongous.io/. That is paid service and has nothing to do with this open-source free project
