### ISSUE TITLE
Failed to build gem native extension on ruby 2.2.3

### ISSUE THREAD

**Issue by duvrai** [bagwanpankaj/humongous#19]
Hi,

When trying `gem install humongous` using ruby 2.2.3 on OS X 10.11, I get this:

    Building native extensions.  This could take a while...
    ERROR:  Error installing humongous:
    	ERROR: Failed to build gem native extension.

        /usr/local/opt/ruby/bin/ruby -r ./siteconf20151209-28172-1e2asiw.rb extconf.rb
    creating Makefile

    make "DESTDIR=" clean

    make "DESTDIR="
    compiling parser.c
    In file included from parser.rl:1:
    ./../fbuffer/fbuffer.h:142:9: warning: variable 'result' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
        if (len > 0) {
            ^~~~~~~
    ./../fbuffer/fbuffer.h:146:12: note: uninitialized use occurs here
        return result;
               ^~~~~~
    ./../fbuffer/fbuffer.h:142:5: note: remove the 'if' if its condition is always true
        if (len > 0) {
        ^~~~~~~~~~~~~
    ./../fbuffer/fbuffer.h:139:20: note: initialize the variable 'result' to silence this warning
        FBuffer *result;
                       ^
                        = NULL
    ./../fbuffer/fbuffer.h:151:47: error: too few arguments provided to function-like macro invocation
        VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                                  ^
    /usr/local/Cellar/ruby/2.2.3/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
    #define rb_str_new(str, len) __extension__ (    \
            ^
    In file included from parser.rl:1:
    ./../fbuffer/fbuffer.h:151:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
        VALUE result = rb_str_new(FBUFFER_PAIR(fb));
              ^        ~~~~~~~~~~
    2 warnings and 1 error generated.
    make: *** [parser.o] Error 1

    make failed, exit code 2

    Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/json-1.6.5 for inspection.
    Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0/json-1.6.5/gem_make.out

**Comment by bagwanpankaj** [comment]
Issue fixed in new version 1.0.1
